/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datum.test;

import datum.utils.User;
import org.apache.http.HttpStatus;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class UserTest extends BaseTest {

    private static final String LIST_USER = "/users";
    private static final String CREATE_USER = "/users";

    @Test
    public void testGETListUsers() {
        given().
                params("page", "2").
        when().
                get(LIST_USER).
        then().
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }

    @Test
    public void testPOSTCreateUser() {
        User user = new User("Rafael", "Engine Test", "rt@gmail.com");
        given().
                body(user).
        when().
                post(CREATE_USER).
        then().
                statusCode(HttpStatus.SC_CREATED).
                body("name", is("Rafael"));
    }
}
