/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datum.test;

import datum.utils.User;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class UserTest {

    @BeforeClass
    public static void setup() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        baseURI = "https://reqres.in";
        basePath = "/api";
    }

    @Test
    public void testGETListUsers() {
        given().
                params("page", "2").
        when().
                get("/users").
        then().
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }

    @Test
    public void testPOSTCreateUser() {
        User user = new User("Rafael", "Engine Test");
        given().
                contentType(ContentType.JSON).
                body(user).
        when().
                post("/users").
        then().
                statusCode(HttpStatus.SC_CREATED).
                body("name", is("Rafael"));
    }
}
