/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datum;

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testApiDatum() {
        assertThat(1, is(1));
    }
}
